Add missing Interface on Widget Defintion
- Refactoring Widget for work with plone.autoforms.directives

Example:

Add the Widget with plone.autoform.directives

```
import from collective.z3cform.norobots.widget import NorobotsFieldWidget

directives.widget('norobots', NorobotsFieldWidget)
norobots = schema.TextLine(
    title = _(u'In order to avoid spam, please answer the question below.'),
    required = True
)
```

It fails with an error

    TypeError: widget_class must implement IWidget or IFieldWidget

Now it works.